# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Homepage2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Dialog_start import Ui_Dialog1
from Dialog_after_start import Ui_Dialog2
from Mainpage import *
import cv2


class Ui_HomeWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.setWindowModality(QtCore.Qt.NonModal)
		MainWindow.resize(966, 732)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("hairstyle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		MainWindow.setAutoFillBackground(False)
		MainWindow.setStyleSheet("background-color: rgb(155, 217, 255);\n"
	"")
		MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
		MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.gridLayout_16 = QtWidgets.QGridLayout()
		self.gridLayout_16.setObjectName("gridLayout_16")
		self.frame = QtWidgets.QFrame(self.centralwidget)
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.gridLayout_16.addWidget(self.frame, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_16, 8, 1, 1, 1)
		self.gridLayout_30 = QtWidgets.QGridLayout()
		self.gridLayout_30.setObjectName("gridLayout_30")
		self.frame_3 = QtWidgets.QFrame(self.centralwidget)
		self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_3.setObjectName("frame_3")
		self.gridLayout_30.addWidget(self.frame_3, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_30, 2, 4, 1, 1)
		self.gridLayout_18 = QtWidgets.QGridLayout()
		self.gridLayout_18.setObjectName("gridLayout_18")
		self.frame_2 = QtWidgets.QFrame(self.centralwidget)
		self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_2.setObjectName("frame_2")
		self.gridLayout_18.addWidget(self.frame_2, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_18, 5, 3, 1, 1)
		self.gridLayout_29 = QtWidgets.QGridLayout()
		self.gridLayout_29.setObjectName("gridLayout_29")
		self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
		self.groupBox_2.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(18)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
		self.groupBox_2.setStyleSheet("background-color: rgb(236, 236, 236);")
		self.groupBox_2.setObjectName("groupBox_2")
		self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_2)
		self.gridLayout_26.setObjectName("gridLayout_26")
		self.gridLayout_21 = QtWidgets.QGridLayout()
		self.gridLayout_21.setObjectName("gridLayout_21")
		self.label_10 = QtWidgets.QLabel(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.label_10.setFont(font)
		self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_10.setObjectName("label_10")
		self.gridLayout_21.addWidget(self.label_10, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_21, 0, 0, 1, 1)
		self.gridLayout_24 = QtWidgets.QGridLayout()
		self.gridLayout_24.setObjectName("gridLayout_24")
		self.label_12 = QtWidgets.QLabel(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
		self.label_12.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.label_12.setFont(font)
		self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_12.setObjectName("label_12")
		self.gridLayout_24.addWidget(self.label_12, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_24, 2, 0, 1, 1)
		self.gridLayout_22 = QtWidgets.QGridLayout()
		self.gridLayout_22.setObjectName("gridLayout_22")
		self.label_11 = QtWidgets.QLabel(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
		self.label_11.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(False)
		font.setWeight(50)
		self.label_11.setFont(font)
		self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.label_11.setObjectName("label_11")
		self.gridLayout_22.addWidget(self.label_11, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_22, 1, 0, 1, 1)
		self.gridLayout_23 = QtWidgets.QGridLayout()
		self.gridLayout_23.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
		self.gridLayout_23.setHorizontalSpacing(20)
		self.gridLayout_23.setObjectName("gridLayout_23")
		self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
		self.lineEdit_3.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		self.lineEdit_3.setFont(font)
		self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.gridLayout_23.addWidget(self.lineEdit_3, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_23, 0, 1, 1, 1)
		self.gridLayout_25 = QtWidgets.QGridLayout()
		self.gridLayout_25.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
		self.gridLayout_25.setObjectName("gridLayout_25")
		self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
		self.lineEdit.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		self.lineEdit.setFont(font)
		self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.lineEdit.setObjectName("lineEdit")
		self.gridLayout_25.addWidget(self.lineEdit, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_25, 1, 1, 1, 1)
		self.gridLayout_27 = QtWidgets.QGridLayout()
		self.gridLayout_27.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
		self.gridLayout_27.setObjectName("gridLayout_27")
		self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
		self.lineEdit_2.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		self.lineEdit_2.setFont(font)
		self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.gridLayout_27.addWidget(self.lineEdit_2, 0, 0, 1, 1)
		self.gridLayout_26.addLayout(self.gridLayout_27, 2, 1, 1, 1)
		self.gridLayout_29.addWidget(self.groupBox_2, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_29, 3, 3, 2, 4)
		self.gridLayout_33 = QtWidgets.QGridLayout()
		self.gridLayout_33.setObjectName("gridLayout_33")
		self.label_7 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_7.setFont(font)
		self.label_7.setObjectName("label_7")
		self.gridLayout_33.addWidget(self.label_7, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_33, 6, 8, 1, 1)
		self.gridLayout_5 = QtWidgets.QGridLayout()
		self.gridLayout_5.setObjectName("gridLayout_5")
		self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
		self.lineEdit_4.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.lineEdit_4.setFont(font)
		self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.gridLayout_5.addWidget(self.lineEdit_4, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_5, 6, 5, 1, 3)
		self.gridLayout_15 = QtWidgets.QGridLayout()
		self.gridLayout_15.setObjectName("gridLayout_15")
		self.label_8 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(True)
		font.setWeight(50)
		self.label_8.setFont(font)
		self.label_8.setObjectName("label_8")
		self.gridLayout_15.addWidget(self.label_8, 1, 1, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_15, 7, 2, 1, 3)
		self.gridLayout_4 = QtWidgets.QGridLayout()
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.label_6 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(False)
		font.setItalic(True)
		font.setWeight(50)
		self.label_6.setFont(font)
		self.label_6.setObjectName("label_6")
		self.gridLayout_4.addWidget(self.label_6, 1, 1, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_4, 6, 2, 1, 3)
		self.gridLayout_14 = QtWidgets.QGridLayout()
		self.gridLayout_14.setObjectName("gridLayout_14")
		self.label = QtWidgets.QLabel(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
		self.label.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setFocusPolicy(QtCore.Qt.NoFocus)
		self.label.setStyleSheet("background-color: rgb(225, 225, 225);")
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label.setObjectName("label")
		self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_14, 7, 5, 1, 3)
		self.gridLayout_20 = QtWidgets.QGridLayout()
		self.gridLayout_20.setObjectName("gridLayout_20")
		self.pushButton = QtWidgets.QPushButton(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
		self.pushButton.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Segoe Script")
		font.setPointSize(18)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton.setFont(font)
		self.pushButton.setStyleSheet("background-color: rgb(4, 214, 18);")
		self.pushButton.setObjectName("pushButton")
		self.gridLayout_20.addWidget(self.pushButton, 0, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_20, 9, 4, 1, 2)
		self.gridLayout_17 = QtWidgets.QGridLayout()
		self.gridLayout_17.setObjectName("gridLayout_17")
		self.label_9 = QtWidgets.QLabel(self.centralwidget)
		font = QtGui.QFont()
		font.setFamily("Myriad Hebrew")
		font.setPointSize(14)
		self.label_9.setFont(font)
		self.label_9.setObjectName("label_9")
		self.gridLayout_17.addWidget(self.label_9, 1, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout_17, 7, 8, 1, 1)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
		self.label_2.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("MV Boli")
		font.setPointSize(48)
		font.setBold(False)
		font.setWeight(50)
		self.label_2.setFont(font)
		self.label_2.setAlignment(QtCore.Qt.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.verticalLayout.addWidget(self.label_2)
		self.gridLayout_2.addLayout(self.verticalLayout, 1, 4, 1, 2)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 26))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusBar = QtWidgets.QStatusBar(MainWindow)
		self.statusBar.setObjectName("statusBar")
		MainWindow.setStatusBar(self.statusBar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		
		self.lineEdit_4.returnPressed.connect(self.cal_time)
		self.pushButton.clicked.connect(self.start_button_clicked)

	def cal_time(self):
		self.graftAmount = self.lineEdit_4.text()
		self.opTime = 8.62*int(self.graftAmount)/3600
		self.label.setText("{:.1f}".format(self.opTime))

	def start_button_clicked(self):
		Dialog1 = QtWidgets.QDialog()
		ui1 = Ui_Dialog1()
		ui1.setupUi(Dialog1)
		Dialog1.show()
		rsp = Dialog1.exec_()
		
		if rsp == QtWidgets.QDialog.Accepted:
			Dialog2 = QtWidgets.QDialog()
			ui2 = Ui_Dialog2()
			ui2.setupUi(Dialog2)
			Dialog2.show()
			rsp2 = Dialog2.exec_()
			
			if rsp2 == QtWidgets.QDialog.Accepted:
				self.window = QtWidgets.QMainWindow()
				self.ui = Ui_MainWindow()
				self.ui.setupUi(self.window)
				self.HN = self.lineEdit_2.text()
				self.ui.label_2.setText("<font color='white'>" + self.HN + "</font>")
				self.TargetAmount = self.lineEdit_4.text()
				self.ui.label_7.setText("<font color='#55ff7f'>" + self.TargetAmount + "</font>")
				self.window.show()
				MainWindow.close()
	
		else:
			pass


	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "PFue-II Homepage"))
		self.groupBox_2.setTitle(_translate("MainWindow", "Patient\'s Info"))
		self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">    Name: </span></p></body></html>"))
		self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">    HN: </span></p></body></html>"))
		self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">    Surname: </span></p></body></html>"))
		self.label_7.setText(_translate("MainWindow", "FUs"))
		self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#005500;\">Calculated Total Operating Time:</span></p></body></html>"))
		self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">Target Graft Amount: </span></p></body></html>"))
		self.label.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
		self.pushButton.setText(_translate("MainWindow", "START"))
		self.label_9.setText(_translate("MainWindow", "hr"))
		self.label_2.setText(_translate("MainWindow", "PFue II"))

import resources_rc

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_HomeWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())


### Don't forget to execute this in commandline before running this code
### pyrcc5 resources.qrc -o resources_rc.py